name: build

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "Unix Makefiles"
  ECVL_VERSION: "v0.3.4"
  EDDL_VERSION: "v0.9.1b"
  PROC: 2
# OPENCV_VERSION: "3.4.12"

jobs:
  build-ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/deps_install
          key: ${{ runner.os }}-${{ env.EDDL_VERSION }}-${{ env.ECVL_VERSION }}-cache-deps

      - name: Install dependencies
        env:
          DEPS_PATH: ${{ runner.workspace }}/deps
          DEPS_INSTALL_PATH: ${{ runner.workspace }}/deps_install
          CACHE: "${{ steps.cache-deps.outputs.cache-hit }}"
        run: |
          sudo apt-get install -y -qq --no-install-recommends git make wget curl
          chmod u+x build_pipeline.sh
          ./build_pipeline.sh ${BUILD_TYPE} "${DEPS_INSTALL_PATH}" "${CMAKE_GENERATOR}" ${EDDL_VERSION} ${ECVL_VERSION} true

      - name: Configure and build
        env:
          DEPS_INSTALL_PATH: ${{ runner.workspace }}/deps_install
        run: |
          mkdir -p build && cd build
          cmake -G"${CMAKE_GENERATOR}" -DBUILD_TYPE=${BUILD_TYPE} -Decvl_DIR=${DEPS_INSTALL_PATH}/ecvl/build/install ..
          cmake --build . --config ${BUILD_TYPE} --parallel ${PROC}
